### ISSUE TITLE
Compatiblity with type2 runtime

### ISSUE THREAD

**Issue by Samueru-sama** [VHSgunzo/uruntime#1]
This issue is just to keep track of the differences wrt to the [current type2 runtime ](https://github.com/AppImage/type2-runtime)and see what will eventually be done for each case. 

`--appimage-extract` is already implemented, however the resulting directory gets named `AppDir` instead of `squashfs-root` so this breaks compatiblity with scripts/programs tha expect a `squashfs-root` when extracting an AppImage. So there are two choices here: 

Either keep the name or guarantee that compatibility.

However calling it `squashfs-root` is also wrong since it can be a dwarfs image instead. 😅

Also `--appimage-extract <regex>` isn't supported either, so doing `--appimage-extract *desktop` will extract the entire AppImage instead of just the top level .desktop file.

-----------------------------------------------------

Here are some other missing features: 

* Checking for the env variable `APPIMAGE_EXTRACT_AND_RUN=1` or the flag `--appimage-extract-and-run` which makes the appimage self extract on `${TMPDIR:-/tmp}` and run, this is often used in CI to avoid issues with fuse not working. 

* export the [env variables](https://docs.appimage.org/packaging-guide/environment-variables.html#id2) `ARGV0` and `APPIMAGE`. There is also `APPDIR` and `OWD` but those are rarely used. 

 * check for a `$0.home` or `$0.config` directory which is used for the portable `$HOME` or `$XDG_CONFIG_HOME` in the [type 2 runtime](https://github.com/AppImage/type2-runtime/blob/main/src/runtime/runtime.c#L1689-L1703)
 
 * `--appimage-updateinfo` which just displays the embedded update information, as far as I know appimageupdatetool doesn't use the flag to update and directly checks the appimage instead.
 
* `--appimage-signature` which I'm not sure if validate needs it in order to work

* `--appimage-offset ` and `--appimage-mount` which I have never used lol

Edit: The type2-runtime also checks the `FUSERMOUNT_PROG` env variable which allows it to work when fuse is on a different location outside PATH.

**Comment by VHSgunzo** [comment]
> export the [env variables](https://docs.appimage.org/packaging-guide/environment-variables.html#id2) ARGV0 and APPIMAGE. There is also APPDIR and OWD but those are rarely used.

this was added in v0.0.1

> squashfs-root
added symlink from AppDir to squashfs-root in v0.0.2 for appimage uruntime
fixed --appimage-mount in v0.0.2

**Comment by VHSgunzo** [comment]
Added in [v0.0.4](https://github.com/VHSgunzo/uruntime/releases/tag/v0.0.4)
