### ISSUE TITLE
AppImage files have broken icon

### ISSUE THREAD

**Issue by mmtrt** [VHSgunzo/uruntime#2]
created `AppImages` using `uruntime` have blank icon as compared to created with `appimagetool`.

![Screenshot_20241120_130343](https://github.com/user-attachments/assets/8bcfe01d-c9d1-4925-9526-93c449f584f6)

**Comment by VHSgunzo** [comment]
what file system did you use?

**Comment by VHSgunzo** [comment]
If DwarFS, then this is not a uruntime problem, but the fact that the file manager (its thumbnail) does not know how to work with DwarFS to get the icon

**Comment by mmtrt** [comment]
`GitKraken-10.5.0.glibc2.25-x86_64-UR.AppImage` is built using `--appimage-mksquashfs` uruntime flag

**Comment by VHSgunzo** [comment]
@mmtrt 
show all the actions and commands that you did to reproduce the problem.
because it's not reproducible for me.
![image](https://github.com/user-attachments/assets/9543e01b-a066-4ae3-9a60-55fc2fc2519e)

**Comment by VHSgunzo** [comment]
and show your AppDir
![image](https://github.com/user-attachments/assets/648b6fb4-b3a4-48f5-b093-957de3bf2d8e)

**Comment by mmtrt** [comment]
`./uruntime-appimage-squashfs-x86_64 --appimage-mksquashfs squashfs-root/ GitKraken-10.5.0.glibc2.25-x86_64-UR.AppImage -comp zstd`

![Screenshot_20241120_151049](https://github.com/user-attachments/assets/5978c647-3f5b-43e7-95b2-5dd4d21a050c)


cat'ing the `uruntime`  to built `appimage` seem to solve the issue.
